M48
; DRILL file {KiCad (6.0.4)} date Fri Aug  4 00:31:11 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-04T00:31:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.200
%
G90
G05
T1
X66.294Y-150.622
X66.294Y-153.162
T2
X102.58Y-168.91
X110.78Y-168.91
T3
X64.175Y-163.068
X71.175Y-163.068
T4
X351.437Y-158.66
T5
X68.0Y-33.0
X68.0Y-172.0
X347.0Y-33.0
X347.0Y-172.0
T0
M30
